name: Package Audit

on:
  push:
    branches:
      - master
    paths:
      - package.json
      - package-lock.json
      - .github/workflows/package-audit.yml
  pull_request:
    branches:
      - master
    paths:
      - package.json
      - package-lock.json
      - .github/workflows/package-audit.yml
  workflow_dispatch:

jobs:
  audit-npm:
    name: npm audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # renovate: tag=v2.4.0

      - name: Setup Node.js environment
        uses: actions/setup-node@56337c425554a6be30cdef71bf441f15be286854 # tag=v3.1.1
        with:
          node-version: lts/*

      - name: Run audit
        run: npm audit --production

  audit-retire:
    name: Retire.js
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # renovate: tag=v2.4.0
        with:
          submodules: true

      - name: Setup Node.js environment
        uses: actions/setup-node@56337c425554a6be30cdef71bf441f15be286854 # tag=v3.1.1
        with:
          node-version: lts/*
          registry-url: https://npm.pkg.github.com
          cache: npm

      - name: Install dependencies
        run: npm ci --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install retire.js
        run: npm i -g retire

      - name: Run audit
        run: retire -n

  audit-trivy:
    name: Trivy scan
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version:
          - 16
    steps:
      - name: Checkout
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # renovate: tag=v2.4.0

      - name: Determine security scan parameters
        id: scanparams
        run: |
          if \
            [ "${{ github.event_name }}" != "pull_request" ] || \
            ([ "${{ github.event.pull_request.head.repo.full_name }}" == "${{ github.event.pull_request.base.repo.full_name }}" ] && [ "${{ github.event.sender.login }}" != "dependabot[bot]" ]) \
          then
            echo ::set-output name=format::template
            echo ::set-output name=template::@/contrib/sarif.tpl
            echo ::set-output name=output::trivy-results.sarif
          else
            echo ::set-output name=format::table
            echo ::set-output name=template::
            echo ::set-output name=output::
          fi

      - name: Security Scan
        uses: aquasecurity/trivy-action@master
        id: scan
        with:
          scan-type: fs
          format: ${{ steps.scanparams.outputs.format }}
          template: ${{ steps.scanparams.outputs.template }}
          output: ${{ steps.scanparams.outputs.output }}

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@d39d5d5c9707b926d517b1b292905ef4c03aa777 # tag=v1.1.2
        with:
          sarif_file: trivy-results.sarif
        if: steps.scanparams.outputs.output != ''
